### PR TITLE
added better feature for order notes, also added history object push …

### PR DESCRIPTION
**Pull request by paulgrever**
…for itemAdded and itemExchange

### CODE REVIEW

**Comment by paulgrever** [comment]
@spencern  this was a update, but it pretty much sums down to passing users around. Now there are history objects created when CS events take place. Also notes, have Author and TIme Stamp and you can add, but can't delete.

**Comment by paulgrever** [comment]
Let me know what you think

**Comment by spencern** [comment]
As we just chatted about:
- Fixing the 'blank' submission.
- Wrap input in a `<form>` element
- Give it a submit button and listen to submit action.

**Comment by paulgrever** [comment]
@spencern  this is done now! !(https://www.dropbox.com/s/8ek5qki4f57g761/Screenshot%202016-01-26%2011.23.29.png?dl=0)

**Comment by paulgrever** [comment]
![Bomb.com](https://www.dropbox.com/s/8ek5qki4f57g761/Screenshot%202016-01-26%2011.23.29.png?dl=0

**Comment by paulgrever** [comment]
Also Github markdown doesn't support inline images.

**Pull request merged**
